spring.application.name=FBK Balkan

# ===============================
# DataSource - SQLite
# ===============================
spring.datasource.url=jdbc:sqlite:fbk-balkan.db?foreign_keys=on
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# SQLite specific
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# ===============================
# JWT Configuration
# ===============================
app.jwtSecret=mySuperSecretKeyThatIsAtLeast512BitsLongForHS512Algorithm12345
app.jwtExpirationMs=86400000

# ===============================
# Logging
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.com.example=DEBUG
